version: '2.1'
services:
  db:
    build: ./db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U docker"]
        interval: 1s
        timeout: 10s
        retries: 5
      
  
  # newsfeeder waits for PostgreSQL server to be ready
  newsfeeder:
    build:
      context: ./newsfeeder
    command: ["/go/bin/newsfeeder"]
    volumes:
      - ./newsfeeder:/go/src/github.com/kansuke231/go-with-vue/newsfeeder
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  
  # api waits for PostgreSQL server AND newsfeeder to be ready
  api:
    build:
      context: ./api
    command: ["/go/bin/api"]
    volumes:
      - ./api:/go/src/github.com/kansuke231/go-with-vue/api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      newsfeeder:
        condition: service_started
    links:
      - db 
      

    
